name: My Test Single Project
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Scala Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Check formatting
        run: sbt scalafmtCheckAll
      - name: Run tests
        run: sbt test
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate coverage
        run: sbt coverage test coverageReport
      - name: SonarCloud scan fixed
        uses: pervasive-cats/sonarcloud-scoverage-fix@v1.0.0
        with:
          scoverageReport: target/scala-2.13/scoverage-report/scoverage.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}